In [153]:
import numpy as np
import pandas as pd

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies = movies.merge(credits,on='title')

movies = movies[['genres','id','overview','keywords','title', 'cast','crew']]

movies.head()

,genres,id,overview,keywords,title,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [154]:
movies.isnull().sum()

genres      0
id          0
overview    3
keywords    0
title       0
cast        0
crew        0
dtype: int64

In [155]:
movies.dropna(inplace=True)

movies.duplicated().sum()

movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [156]:
import ast
ast.literal_eval

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [157]:
movies['genres']= movies['genres'].apply(convert)

In [158]:
movies.head()

,genres,id,overview,keywords,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [159]:
movies['keywords']= movies['keywords'].apply(convert)

In [160]:
movies.head()

,genres,id,overview,keywords,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [161]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [162]:
def convert3(obj):
    L = []
    counter = 0  # 'conuter' වෙනුවට 'counter' ලෙස නිවැරදි විය යුතුයි
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [163]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [164]:
movies.head()

,genres,id,overview,keywords,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [165]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [166]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [167]:
movies.head()

,genres,id,overview,keywords,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [168]:
movies.overview[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [169]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.head()

,genres,id,overview,keywords,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [170]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies.head()

,genres,id,overview,keywords,title,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski]
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton]

In [171]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies.head()

,genres,id,overview,keywords,title,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [172]:
new_df = movies[['id','title','tags']]

In [173]:
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [174]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x).lower())

C:\Users\MSI\AppData\Local\Temp\ipykernel_6700\274634086.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x).lower())

In [175]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [176]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " j a k e  s u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " s a m  w o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " n e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " z o e  s a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " d r .  g r a c e  a u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " s i g o u r n e y  w e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " s t e p h e n  l a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " t r u d y  c h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " m i c h e l l e  r o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " s e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " g i o v a n n i  r i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " n o r m  s p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " j o e l  d a v i d  m o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " m o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " c c h  p o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " e y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " w e s  s t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " t s u \' t e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " l a z  a l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " d r .  m a x  p a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " d i l e e p  r a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " l y l e  w a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " m a t t  g e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " p r i v a t e  f i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " s e a n  a n t h o n y  m o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " c r y o  v a u l t  m e d  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " j a s o n  w h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " v e n t u r e  s t a r  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " s c o t t  l a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " l o c k  u p  t r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " k e l l y  k i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " s h u t t l e  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " j a m e s  p a t r i c k  p i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " s h u t t l e  c o - p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " s e a n  p a t r i c k  m u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " s h u t t l e  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " p e t e r  d i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " t r a c t o r  o p e r a t o r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " k e v i n  d o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " k e l s o n  h e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  g u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " d a v i d  v a n  h o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  n a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " j a c o b  t o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " s u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " m i c h a e l  b l a i n - r o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " s u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " j o n  c u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " l u k e  h a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " w o o d y  s c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " h o r s e  c l a n  l e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " p e t e r  m e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " l i n k  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " s o n i a  y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " j a h n e l  c u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " i l r a m  c h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " n a \' v i  c h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " k y l a  w a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " l i s a  r o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " d e b r a  w i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " c h r i s  m a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " t a y l o r  k i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " j o d i e  l a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " j u l i e  l a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " c u l l e n  b .  m a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " j o s e p h  b r a d y  m a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " f r a n k i e  t o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " a u s t i n  w i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " s a r a  w i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " t a m i c a  w a s h i n g t o n - m i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " l u c y  b r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " n a t h a n  m e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " g e r r y  b l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " m a t t h e w  c h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " p a u l  y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " o p  c e n t e r  d u t y  o f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " w r a y  w i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " j a m e s  g a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " m e l v i n  l e n o  c l a r k  i i i " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " c a r v o n  f u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " b r a n d o n  j e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " m i c a h  m o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " h a n n i y a h  m u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " c h r i s t o p h e r  n o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " c h r i s t a  o l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " a p r i l  m a r i e  t h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " b r a v i t a  a .  t h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " m i n i n g  c h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " c o l i n  b l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " v e t e r a n  m i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " m i k e  b o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " r i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e " :  " m a t t  c l a y t o n " ,  " o r d e r " :  6 2 } ,  { " c a s t _ i d " :  8 4 ,  " c h a r a c t e r " :  " n a v \' i  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " ,  " g e n d e r " :  1 ,  " i d " :  1 4 7 8 9 8 ,  " n a m e " :  " n i c o l e  d i o n n e " ,  " o r d e r " :  6 3 } ,  { " c a s t _ i d " :  8 5 ,  " c h a r a c t e r " :  " t r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 0 ,  " n a m e " :  " j a m i e  h a r r i s o n " ,  " o r d e r " :  6 4 } ,  { " c a s t _ i d " :  8 6 ,  " c h a r a c t e r " :  " t r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 1 ,  " n a m e " :  " a l l a n  h e n r y " ,  " o r d e r " :  6 5 } ,  { " c a s t _ i d " :  8 7 ,  " c h a r a c t e r " :  " g r o u n d  t e c h n i c i a n  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 2 0 7 2 8 2 ,  " n a m e " :  " a n t h o n y  i n g r u b e r " ,  " o r d e r " :  6 6 } ,  { " c a s t _ i d " :  8 8 ,  " c h a r a c t e r " :  " f l i g h t  c r e w  m e c h a n i c  ( u n 

In [177]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [178]:
vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [179]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [180]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [181]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\MSI\AppData\Local\Temp\ipykernel_6700\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [182]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d [ { " c a s t _ i d " : 2 4 2 , " c h a r a c t e r " : " j a k e s u l l y " , " c r e d i t _ i d " : " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " , " g e n d e r " : 2 , " i d " : 6 5 7 3 1 , " n a m e " : " s a m w o r t h i n g t o n " , " o r d e r " : 0 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " n e y t i r i " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " , " g e n d e r " : 1 , " i d " : 8 6 9 1 , " n a m e " : " z o e s a l d a n a " , " o r d e r " : 1 } , { " c a s t _ i d " : 2 5 , " c h a r a c t e r " : " d r . g r a c e a u g u s t i n e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " , " g e n d e r " : 1 , " i d " : 1 0 2 0 5 , " n a m e " : " s i g o u r n e y w e a v e r " , " o r d e r " : 2 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " c o l . q u a r i t c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " , " g e n d e r " : 2 , " i d " : 3 2 7 4 7 , " n a m e " : " s t e p h e n l a n g " , " o r d e r " : 3 } , { " c a s t _ i d " : 5 , " c h a r a c t e r " : " t r u d y c h a c o n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " , " g e n d e r " : 1 , " i d " : 1 7 6 4 7 , " n a m e " : " m i c h e l l e r o d r i g u e z " , " o r d e r " : 4 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " s e l f r i d g e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " , " g e n d e r " : 2 , " i d " : 1 7 7 1 , " n a m e " : " g i o v a n n i r i b i s i " , " o r d e r " : 5 } , { " c a s t _ i d " : 7 , " c h a r a c t e r " : " n o r m s p e l l m a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " , " g e n d e r " : 2 , " i d " : 5 9 2 3 1 , " n a m e " : " j o e l d a v i d m o o r e " , " o r d e r " : 6 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " m o a t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " , " g e n d e r " : 1 , " i d " : 3 0 4 8 5 , " n a m e " : " c c h p o u n d e r " , " o r d e r " : 7 } , { " c a s t _ i d " : 1 1 , " c h a r a c t e r " : " e y t u k a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " , " g e n d e r " : 2 , " i d " : 1 5 8 5 3 , " n a m e " : " w e s s t u d i " , " o r d e r " : 8 } , { " c a s t _ i d " : 1 0 , " c h a r a c t e r " : " t s u \' t e y " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " , " g e n d e r " : 2 , " i d " : 1 0 9 6 4 , " n a m e " : " l a z a l o n s o " , " o r d e r " : 9 } , { " c a s t _ i d " : 1 2 , " c h a r a c t e r " : " d r . m a x p a t e l " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " , " g e n d e r " : 2 , " i d " : 9 5 6 9 7 , " n a m e " : " d i l e e p r a o " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " l y l e w a i n f l e e t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " , " g e n d e r " : 2 , " i d " : 9 8 2 1 5 , " n a m e " : " m a t t g e r a l d " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " p r i v a t e f i k e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " , " g e n d e r " : 2 , " i d " : 1 5 4 1 5 3 , " n a m e " : " s e a n a n t h o n y m o r a n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " c r y o v a u l t m e d t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " , " g e n d e r " : 2 , " i d " : 3 9 7 3 1 2 , " n a m e " : " j a s o n w h y t e " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " v e n t u r e s t a r c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " , " g e n d e r " : 2 , " i d " : 4 2 3 1 7 , " n a m e " : " s c o t t l a w r e n c e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " l o c k u p t r o o p e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " , " g e n d e r " : 2 , " i d " : 9 8 6 7 3 4 , " n a m e " : " k e l l y k i l g o u r " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " s h u t t l e p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 2 7 , " n a m e " : " j a m e s p a t r i c k p i t t " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " s h u t t l e c o - p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " , " g e n d e r " : 0 , " i d " : 1 1 8 0 9 3 6 , " n a m e " : " s e a n p a t r i c k m u r p h y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " s h u t t l e c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " , " g e n d e r " : 2 , " i d " : 1 0 1 9 5 7 8 , " n a m e " : " p e t e r d i l l o n " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " t r a c t o r o p e r a t o r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " , " g e n d e r " : 0 , " i d " : 9 1 4 4 3 , " n a m e " : " k e v i n d o r m a n " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " d r a g o n g u n s h i p p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " , " g e n d e r " : 2 , " i d " : 1 7 3 3 9 1 , " n a m e " : " k e l s o n h e n d e r s o n " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " d r a g o n g u n s h i p g u n n e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 3 6 , " n a m e " : " d a v i d v a n h o r n " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " d r a g o n g u n s h i p n a v i g a t o r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " , " g e n d e r " : 0 , " i d " : 2 1 5 9 1 3 , " n a m e " : " j a c o b t o m u r i " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " s u i t # 1 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " , " g e n d e r " : 0 , " i d " : 1 4 3 2 0 6 , " n a m e " : " m i c h a e l b l a i n - r o z g a y " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 4 4 , " c h a r a c t e r " : " s u i t # 2 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " , " g e n d e r " : 2 , " i d " : 1 6 9 6 7 6 , " n a m e " : " j o n c u r r y " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 4 6 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " , " g e n d e r " : 0 , " i d " : 1 0 4 8 6 1 0 , " n a m e " : " l u k e h a w k e r " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 4 7 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " n a m e " : " w o o d y s c h u l t z " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 4 8 , " c h a r a c t e r " : " h o r s e c l a n l e a d e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " , " g e n d e r " : 2 , " i d " : 6 8 2 7 8 , " n a m e " : " p e t e r m e n s a h " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 4 9 , " c h a r a c t e r " : " l i n k r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 7 , " n a m e " : " s o n i a y e e " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " , " g e n d e r " : 1 , " i d " : 1 2 0 7 2 4 8 , " n a m e " : " j a h n e l c u r f m a n " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " n a m e " : " i l r a m c h o i " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " n a \' v i c h i l d " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 9 , " n a m e " : " k y l a w a r r e n " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 0 , " n a m e " : " l i s a r o u m a i n " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " , " g e n d e r " : 1 , " i d " : 8 3 1 0 5 , " n a m e " : " d e b r a w i l s o n " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 3 , " n a m e " : " c h r i s m a l a " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 1 , " n a m e " : " t a y l o r k i b b y " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 2 , " n a m e " : " j o d i e l a n d a u " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 4 , " n a m e " : " j u l i e l a m m " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 7 , " n a m e " : " c u l l e n b . m a d d e n " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 9 , " n a m e " : " j o s e p h b r a d y m a d d e n " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 2 , " n a m e " : " f r a n k i e t o r r e s " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " , " g e n d e r " : 1 , " i d " : 1 1 5 8 6 0 0 , " n a m e " : " a u s t i n w i l s o n " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " , " g e n d e r " : 1 , " i d " : 9 8 3 7 0 5 , " n a m e " : " s a r a w i l s o n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 3 , " n a m e " : " t a m i c a w a s h i n g t o n - m i l l e r " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " , " g e n d e r " : 1 , " i d " : 1 1 4 5 0 9 8 , " n a m e " : " l u c y b r i a n t " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " , " g e n d e r " : 2 , " i d " : 3 3 3 0 5 , " n a m e " : " n a t h a n m e i s t e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 4 , " n a m e " : " g e r r y b l a i r " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " , " g e n d e r " : 2 , " i d " : 3 3 3 1 1 , " n a m e " : " m a t t h e w c h a m b e r l a i n " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 5 , " n a m e " : " p a u l y a t e s " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " o p c e n t e r d u t y o f f i c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 6 , " n a m e " : " w r a y w i l s o n " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " , " g e n d e r " : 2 , " i d " : 5 4 4 9 2 , " n a m e " : " j a m e s g a y l y n " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 7 , " n a m e " : " m e l v i n l e n o c l a r k i i i " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 8 , " n a m e " : " c a r v o n f u t r e l l " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 9 , " n a m e " : " b r a n d o n j e l k e s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 0 , " n a m e " : " m i c a h m o c h " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 1 , " n a m e " : " h a n n i y a h m u h a m m a d " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 7 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 2 , " n a m e " : " c h r i s t o p h e r n o l e n " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 8 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 3 , " n a m e " : " c h r i s t a o l i v e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 9 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 4 , " n a m e " : " a p r i l m a r i e t h o m a s " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 8 0 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 5 , " n a m e " : " b r a v i t a a . t h r e a t t " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 8 1 , " c h a r a c t e r " : " m i n i n g c h i e f ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 6 , " n a m e " : " c o l i n b l e a s d a l e " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 8 2 , " c h a r a c t e r " : " v e t e r a n m i n e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " , " g e n d e r " : 0 , " i d " : 1 0 7 9 6 9 , " n a m e " : " m i k e b o d n a r " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 8 3 , " c h a r a c t e r " : " r i c h a r d ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 8 , " n a m e " : " m a t t c l a y t o n " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 8 4 , " c h a r a c t e r " : " n a v \' i ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " , " g e n d e r " : 1 , " i d " : 1 4 7 8 9 8 , " n a m e " : " n i c o l e d i o n n e " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 8 5 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 0 , " n a m e " : " j a m i e h a r r i s o n " , " o r d e r " : 6 4 } , { " c a s t _ i d " : 8 6 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 1 , " n a m e " : " a l l a n h e n r y " , " o r d e r " : 6 5 } , { " c a s t _ i d " : 8 7 , " c h a r a c t e r " : " g r o u n d t e c h n i c i a n ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " , " g e n d e r " : 2 , " i d " : 1 2 0 7 2 8 2 , " n a m e " : " a n t h o n y i n g r u b e r " , " o r d e r " : 6 6 } , { " c a s t _ i d " : 8 8 , " c h a r a c t e r " : " f l i g h t c r e w m e c h a n i c ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 3 , " n a m e " : " a s h l e y j e f f e r y " , " o r d e r " : 6 7 } , { " c a s t _ i d " : 1 4 , " c h a r a c t e r " : " s a m s o n p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 9 " , " g e n d e r " : 0 , " i d " : 9 8 2 1 6 , " n a m e " : " d e a n k n o w s l e y " , " o r d e r " : 6 8 } , { " c a s t _ i d " : 8 9 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 b " , " g e n d e r " : 0 , " i d " : 1 2 0 1 3 9 9 , " n a m e " : " j o s e p h m i k a - h u n t " , " o r d e r " : 6 9 } , { " c a s t _ i d " : 9 0 , " c h a r a c t e r " : " b a n s h e e ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 f " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " n a m e " : " t e r r y n o t a r y " , " o r d e r " : 7 0 } , { " c a s t _ i d " : 9 1 , " c h a r a c t e r " : " s 

In [183]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.09284767, 0.06085806, ..., 0.02431083, 0.02668803,
        0.        ],
       [0.09284767, 1.        , 0.06780635, ..., 0.02708645, 0.        ,
        0.        ],
       [0.06085806, 0.06780635, 1.        , ..., 0.02663118, 0.        ,
        0.        ],
       ...,
       [0.02431083, 0.02708645, 0.02663118, ..., 1.        , 0.07007128,
        0.04732485],
       [0.02668803, 0.        , 0.        , ..., 0.07007128, 1.        ,
        0.05195243],
       [0.        , 0.        , 0.        , ..., 0.04732485, 0.05195243,
        1.        ]], shape=(4806, 4806))

In [186]:
def recomend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
    return

recomend('Avatar')

Titan A.E.
Small Soldiers
Independence Day
Aliens vs Predator: Requiem
Ender's Game

In [188]:
import pickle

pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [190]:
import pickle

pickle.dump(similarity,open('similarity.pkl','wb'))